"""create verification tokens table

Revision ID: 78a455b991f3
Revises: ee183bbc294c
Create Date: 2026-07-26 22:30:40.999806

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "78a455b991f3"
down_revision: Union[str, Sequence[str], None] = "ee183bbc294c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verification_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column(
            "token_type",
            sa.Enum(
                "EMAIL_VERIFICATION",
                "PASSWORD_RESET",
                "EMAIL_CHANGE",
                name="verificationtokentype",
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_verification_tokens_expires_at"),
        "verification_tokens",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_tokens_user_id"),
        "verification_tokens",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_verification_tokens_user_type",
        "verification_tokens",
        ["user_id", "token_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_verification_tokens_user_type", table_name="verification_tokens")
    op.drop_index(
        op.f("ix_verification_tokens_user_id"), table_name="verification_tokens"
    )
    op.drop_index(
        op.f("ix_verification_tokens_expires_at"), table_name="verification_tokens"
    )
    op.drop_table("verification_tokens")
    verification_token_type = sa.Enum(
        "EMAIL_VERIFICATION",
        "PASSWORD_RESET",
        "EMAIL_CHANGE",
        name="verificationtokentype",
    )

    verification_token_type.drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###
